
export const BASIC_HAMA_COLORS = 'BASIC_HAMA_COLORS';
export const PASTEL_HAMA_COLORS = 'PASTEL_HAMA_COLORS';
export const TRANSPARENT_HAMA_COLORS = 'TRANSPARENT_HAMA_COLORS';
export const METAL_HAMA_COLORS = 'METAL_HAMA_COLORS';
export const IKEA_BEADS_COLORS = 'IKEA_BEADS_COLORS';
