export default {
	de_DE: {
		START_EMPTY_EDITOR: 'Starte mit einem leeren Editor',
		START_WITH_PICTURE: 'Starte mit einer Bildvorlage',
		INSERT_LINK: 'Füge einen Link zu einem Bild ein',
		UPLOAD_IMAGE: 'oder lade ein Bild von der Festplatte',
		NUMBER_OF_TABLES_LABEL: 'Tablet Größe:',
		NUMBER_OF_TABLES_LABEL_CROSS: 'x',
		SEARCH_PLACEHOLDER: 'suche...',
		COLOR_RED: 'Rot',
		COLOR_BLACK: 'Schwarz',
		COLOR_WHITE: 'Weis',
		ZOOM: 'Zoom',
		PREVIEW: 'Vorschau',
		USE_IMAGE: 'Dieses Bild benutzen',
		PICTURE_ERROR: 'Bild nicht gefunden oder falsches Format',
		WIDTH: 'Breite',
		HEIGHT: 'Höhe',
		PIXEL: 'Pixel',
		TYPE: 'Bildtyp',
		CHOOSE_ALGORITHM: 'Wähle einen Algorithmus',
		CHOOSE_MAX_SIZE: 'Wähle eine maximale Größe',
		CHOOSE_SCALE_OPTION: 'Wähle Art der Verkleinerung',
		RESIZE_NEAREST_NEIGHBOR: 'Nächster Nachbar',
		RESIZE_BILINEAR: 'Bilinear',
		RESIZE_BICUBIC: 'Bicubisch',
		RESIZE_HERMITE: 'Hermite',
		RESIZE_BEZIER: 'Bezier',
		PLATES: 'Platten',
		CHOOSE_BEADS: 'Wähle Perlentypen',
		BASIC_HAMA_COLORS: 'Basisfarben HAMA',
		PASTEL_HAMA_COLORS: 'Pastelfarben HAMA',
		TRANSPARENT_HAMA_COLORS: 'Transparente HAMA',
		METAL_HAMA_COLORS: 'Metalfarben HAMA',
		IKEA_BEADS_COLORS: 'IKEA Farben',
		CONVERT_PICTURE: 'Bild umwandeln',
		RESIZE_OPTION_SCALE_CUBIC: 'mit Faktor 2^x',
		RESIZE_OPTION_SCALE_MAX_SPACE: 'maximale Fläche nutzen',
	},
};
