export default {
	de_DE: {
		START_EMPTY_EDITOR: 'Starte mit einem leeren Editor',
		START_WITH_PICTURE: 'Starte mit einer Bildvorlage',
		INSERT_LINK: 'Füge einen Link zu einem Bild ein',
		UPLOAD_IMAGE: 'oder lade ein Bild von der Festplatte',
		NUMBER_OF_TABLES_LABEL: 'Tablet Größe:',
		NUMBER_OF_TABLES_LABEL_CROSS: 'x',
		SEARCH_PLACEHOLDER: 'suche...',
		COLOR_RED: 'Rot',
		COLOR_BLACK: 'Schwarz',
		COLOR_WHITE: 'Weis',
		ZOOM: 'Zoom',
		PREVIEW: 'Vorschau',
		USE_IMAGE: 'Dieses Bild benutzen',
		PICTURE_ERROR: 'Bild nicht gefunden oder falsches Format',
		WIDTH: 'Breite',
		HEIGHT: 'Höhe',
		PIXEL: 'Pixel',
		TYPE: 'Bildtyp',
		CHOOSE_ALGORITHM: 'Wähle einen Algorithmus',
		CHOOSE_MAX_SIZE: 'Wähle eine maximale Größe',
		CHOOSE_SCALE_OPTION: 'Wähle Art der Verkleinerung',
		nearestNeighbor: 'Nächster Nachbar',
		bilinearInterpolation: 'Bilinear',
		bicubicInterpolation: 'Bicubisch',
		hermiteInterpolation: 'Hermite',
		bezierInterpolation: 'Bezier',
		PLATES: 'Platten',
		CHOOSE_BEADS: 'Wähle Perlentypen',
		HAMA_BASIC: 'Basisfarben HAMA',
		HAMA_PASTEL: 'Pastelfarben HAMA',
		HAMA_TRANSPARENT: 'Transparente HAMA',
		HAMA_METAL: 'Metalfarben HAMA',
		IKEA: 'IKEA Farben',
		CONVERT_PICTURE: 'Bild umwandeln',
		RESIZE_OPTION_SCALE_CUBIC: 'mit Faktor 2^x',
		RESIZE_OPTION_SCALE_MAX_SPACE: 'maximale Fläche nutzen',
		TRANSFER_TO_EDITOR: 'Dieses Bild im Editor nutzen',
		PRINT_PREVIEW: 'Druckansicht',
		NO_BEAD_SET: 'Keine Perle gesetzt',

		H01_NAME: 'WHITE',
		H02_NAME: 'CREAM',
		H03_NAME: 'YELLOW',
		H04_NAME: 'ORANGE',
		H05_NAME: 'RED',
		H06_NAME: 'PINK',
		H07_NAME: 'PURPLE',
		H08_NAME: 'BLUE',
		H09_NAME: 'LIGHT BLUE',
		H10_NAME: 'GREEN',
		H11_NAME: 'LIGHT GREEN',
		H12_NAME: 'BROWN',
		H17_NAME: 'GREY',
		H18_NAME: 'BLACK',
		H19_NAME: 'TRANSPARENT',
		H20_NAME: 'RED BROWN',
		H21_NAME: 'LIGHT BROWN',
		H22_NAME: 'DARK RED',
		H26_NAME: 'FLESH',
		H27_NAME: 'BEIGE',
		H28_NAME: 'DARK GREEN',
		H29_NAME: 'CLARET',
		H30_NAME: 'BURGUNDY',
		H31_NAME: 'TURQUOISE',
		H32_NAME: 'FUCHSIA',
		H43_NAME: 'PASTEL YELLOW',
		H44_NAME: 'PASTEL RED',
		H45_NAME: 'PASTEL PURPLE',
		H46_NAME: 'PASTEL BLUE',
		H47_NAME: 'PASTEL GREEN',
		H48_NAME: 'PASTEL PINK',
		H49_NAME: 'AZURE',
		H60_NAME: 'TEDDY BEAR',
		H61_NAME: 'GOLD',
		H62_NAME: 'SILVER',
		H63_NAME: 'BRONZE',

		ID: 'Id',
		COLOR: 'Farbe',
		SUM: 'Summe',
		TOTAL_USED_BEADS: 'Insgesamt benötigte Perlen',
		NO_BEAD: 'Keine Perle',
		BACK_TO_EDITOR_MODE: 'Zurück zum Editor',
		FILTER_COLOR: 'Farben filter',
		URL_TO_SHARE: 'Url zum Teilen',
		LINK_TO_SHARE_CANVAS: 'Link zum teilen des aktuellen Editors',
		HOME_INTRODUCTION: 'Online Tool zum Erstellen von Mustern/ Anleitungen für Bügelperlen aus Bilddateien.',
		CONTACT: 'Kontakt',
	},
};
